title: Dungeon Delvers
author: rexdefuror
email: srdjan.debic@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Dungeons and Dragons story blog - adventures that happened and 
  are happening on Dungeon Delvers discord server.
show_excerpts: false # set to true to show excerpts on the homepage
baseurl: "/dungeondelvers"
root: "/dungeondelvers"
url: "https://rexdefuror.github.io"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Dungeon Delvers
  tagline: Dungeons&Dragons, Campaigns, Worlds...
  date_format: "%b %-d, %Y"
  style: red
  showNav: false
  showPicker: false
  analytics_id: UA-154654086-1

  # generate social links in footer
  social_links:
    twitter: rexdefuror
    rss: rss
    discord: https://discord.gg/aMVNbEt
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed
